# Generated by Django 4.2.4 on 2023-09-09 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payme.item')),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=24)),
                ('wants_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payme.orderdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
