# Generated by Django 4.2.4 on 2023-08-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payme.orderdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
