# Generated by Django 4.2.4 on 2023-08-26 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_remove_customordermodel_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customordermodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customordermodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
