# Generated by Django 4.2.4 on 2023-08-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0003_alter_merchattransactionsmodel_options'),
        ('shop', '0003_remove_customordermodel_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payme.item')),
            ],
        ),
    ]
