# Generated by Django 4.2.4 on 2023-08-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customordermodel_full_name_customordermodel_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customordermodel',
            name='product',
        ),
    ]
