# Generated by Django 4.2.4 on 2023-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_customordermodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customordermodel',
            name='wants_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
