name: GitHub-CI

on: [push]

jobs:
  check-unit-tests:
    runs-on: ubuntu-latest
    environment: env
    env:
      DJANGO_SETTINGS_MODULE: mysite.settings
      DEBUG: ${{ secrets.DEBUG }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      PAYME_ID: ${{ secrets.PAYME_ID }}
      PAYME_KEY: ${{ secrets.PAYME_KEY }}
      PAYME_URL: ${{ secrets.PAYME_URL }}
      PAYME_CALL_BACK_URL: ${{ secrets.PAYME_CALL_BACK_URL }}
      PAYME_MIN_AMOUNT: ${{ vars.PAYME_MIN_AMOUNT }}
      PAYME_ACCOUNT: ${{ secrets.PAYME_ACCOUNT }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements
        run: pip3 install -r requirements.txt

      - name: Run Tests
        run: |
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py test
