name: GitHub-CI

on: [push]

jobs:
  check-unit-tests:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULEL: mysite.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Requirements
        run: pip3 install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: ${{ env.DEBUG }}
          SECRET_KEY: ${{ env.SECRET_KEY }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}

          PAYME_ID: ${{ env.PAYME_ID }}
          PAYME_KEY: ${{ env.PAYME_KEY }}
          PAYME_URL: ${{ env.PAYME_URL }}
          PAYME_CALL_BACK_URL: ${{ env.PAYME_CALL_BACK_URL }}
          PAYME_MIN_AMOUNT: ${{ env.PAYME_MIN_AMOUNT }}
          PAYME_ACCOUNT: ${{ env.PAYME_ACCOUNT }}

        run: |
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py test
